# ==========================================
# TEMA DO HARRY ASSISTENT
# ==========================================

# Cores principais
COR_FUNDO = "#1E1E1E"
COR_MENU_LATERAL = "#252526"
COR_COMPONENTE = "#2D2D30"
COR_COMPONENTE_HOVER = "#37373D"
COR_BORDA = "#3F3F46"

# Cores de destaque
COR_PRIMARIA = "#2563EB"
COR_PRIMARIA_HOVER = "#1D4ED8"

COR_SUCESSO = "#22C55E"
COR_ATENCAO = "#F59E0B"
COR_ERRO = "#EF4444"
COR_INFORMACAO = "#3B82F6"

# Textos
COR_TEXTO = "#FFFFFF"
COR_TEXTO_SECUNDARIO = "#A1A1AA"

# Fontes
FONTE_PADRAO = "Segoe UI"
FONTE_EMOJI = "Segoe UI Emoji"

TAMANHO_TITULO = 28
TAMANHO_SUBTITULO = 15
TAMANHO_TEXTO = 14
TAMANHO_DESTAQUE = 27

# Dimensões
LARGURA_MENU = 220
RAIO_COMPONENTE = 12